[package]
name = "query_exec"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
txn_storage = { git = "https://github.com/rotaki/txn_storage.git", branch = "master" }